apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
  namespace: sunny-influence-267611
spec:
  selector:
    app: mysql-db
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql-db-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  labels:
    app: mysql-db
  namespace: sunny-influence-267611
spec:
  selector:
    matchLabels:
      app: mysql-db
  serviceName: "mysql-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-db
        image: mysql:latest
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
        ports:
        - containerPort: 3306
          name: mysql-db-port
        volumeMounts:
        - name: mysql-db-data
          mountPath: /var/lib/mysql/data
  volumeClaimTemplates:
  - metadata:
      name: mysql-db-data
      labels:
        app: mysql-db
      namespace: sunny-influence-267611
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi
